/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.randomsoftware.java2d;

import ru.randomsoftware.java2d.generators.MiddlePointLineGenerator;
import ru.randomsoftware.java2d.renderers.Renderer;
import ru.randomsoftware.java2d.renderers.RendererBW;
import ru.randomsoftware.java2d.rules.NumericRule;
import ru.randomsoftware.java2d.simulations.LineCellularAutomate;

import java.util.List;

public class App {

    private static final int WIDTH = 1400;
    private static final int HEIGHT = 800;
    private static final LineCellularAutomate AUTOMATE = new LineCellularAutomate(
            new MiddlePointLineGenerator(),
            new NumericRule(161),
            WIDTH
    );

    public void run() {
        Renderer<Boolean> renderer = new RendererBW(WIDTH, HEIGHT);
        List<List<Boolean>> matrix = AUTOMATE.buildGenerations(HEIGHT);
        renderer.render(matrix);
    }

    public static void main(String[] args) {
        App app = new App();
        app.run();
    }
}
